CREATE TABLE IF NOT EXISTS products (
  id       SERIAL PRIMARY KEY,
  name     VARCHAR(255) NOT NULL,
  brand    VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  stock    INTEGER NOT NULL,
  price    NUMERIC(10,2) NOT NULL,
  available BOOLEAN NOT NULL
);